version: '3'

services:
  redis:
    container_name: go-messenger.redis
    image: 'docker.io/bitnami/redis:6.0-debian-10'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    expose:
         - 6379
    volumes:
      - 'redis_go_chat_data:/bitnami/redis/data'

  # mongodb:
  #   image: docker.io/bitnami/mongodb:4.4-debian-10
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: user
  #     MONGO_INITDB_ROOT_PASSWORD: vking34
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - 'mongodb_data:/bitnami/mongodb'

volumes:
  redis_go_chat_data:
    driver: local
  
  # mongodb_go_chat_data:
  #   driver: local
